# Generated by Django 3.2 on 2021-05-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Status',
            new_name='status',
        ),
    ]
